2025-09-22 23:10:05,633 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:10:05,633 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:05,635 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:10:05,636 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:05,637 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:10:05,637 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:05,640 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:10:05,641 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:10:05,642 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:05,646 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:10:05,646 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:05,649 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:10:08,296 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:10:08,302 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.username, users.email, users.hashed_password, users.`role`, users.otp, users.otp_expiry, users.created_at, users.updated_at 
FROM users 
WHERE users.username = %s
2025-09-22 23:10:08,302 - sqlalchemy.engine.Engine - INFO - [generated in 0.00066s] ('Jonu sharma',)
2025-09-22 23:10:08,307 - main - INFO - Creating a  new course = DBMS
2025-09-22 23:10:08,307 - main - ERROR - Error creating course : create_course() missing 2 required positional arguments: 'Course_desc' and 'Course_duration'
Traceback (most recent call last):
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\app\routes\routes.py", line 170, in create_course
    new_courses =await crud.create_course(db,course)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: create_course() missing 2 required positional arguments: 'Course_desc' and 'Course_duration'
2025-09-22 23:10:08,309 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-09-22 23:10:37,636 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:10:37,637 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:37,638 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:10:37,639 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:37,640 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:10:37,641 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:37,643 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:10:37,643 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:10:37,644 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:37,647 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:10:37,648 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:37,651 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:10:45,316 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:10:45,317 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:45,319 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:10:45,319 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:45,321 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:10:45,321 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:45,323 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:10:45,324 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:10:45,324 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:45,328 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:10:45,329 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:45,332 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:10:47,992 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:10:47,992 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:47,995 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:10:47,995 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:47,996 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:10:47,997 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:47,998 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:10:47,999 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:10:48,000 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:48,004 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:10:48,004 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:10:48,007 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:11:16,793 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:11:16,794 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:11:16,796 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:11:16,797 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:11:16,798 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:11:16,799 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:11:16,801 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:11:16,801 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:11:16,802 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:11:16,817 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:11:16,817 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:11:16,821 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:11:18,248 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:11:18,253 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.username, users.email, users.hashed_password, users.`role`, users.otp, users.otp_expiry, users.created_at, users.updated_at 
FROM users 
WHERE users.username = %s
2025-09-22 23:11:18,254 - sqlalchemy.engine.Engine - INFO - [generated in 0.00071s] ('Jonu sharma',)
2025-09-22 23:11:18,258 - main - INFO - Creating a  new course = DBMS
2025-09-22 23:11:18,258 - main - ERROR - Error creating course : create_course() missing 2 required positional arguments: 'Course_desc' and 'Course_duration'
Traceback (most recent call last):
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\app\routes\routes.py", line 170, in create_course
    new_courses =await crud.create_course(db,course)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: create_course() missing 2 required positional arguments: 'Course_desc' and 'Course_duration'
2025-09-22 23:11:18,259 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-09-22 23:12:24,890 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:12:24,891 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:24,893 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:12:24,893 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:24,894 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:12:24,895 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:24,896 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:12:24,897 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:12:24,897 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:24,901 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:12:24,901 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:24,905 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:12:31,965 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:12:31,966 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:31,968 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:12:31,968 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:31,969 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:12:31,970 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:31,972 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:12:31,973 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:12:31,973 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:31,976 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:12:31,977 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:31,980 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:12:44,170 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:12:44,176 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:44,179 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:12:44,180 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:44,181 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:12:44,183 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:44,185 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:12:44,187 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:12:44,188 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:44,195 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:12:44,195 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:12:44,200 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:17:55,813 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:17:55,813 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:17:55,816 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:17:55,816 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:17:55,818 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:17:55,819 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:17:55,821 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:17:55,821 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:17:55,822 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:17:55,827 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:17:55,828 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:17:55,831 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:19:11,219 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:19:11,226 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.username, users.email, users.hashed_password, users.`role`, users.otp, users.otp_expiry, users.created_at, users.updated_at 
FROM users 
WHERE users.username = %s
2025-09-22 23:19:11,226 - sqlalchemy.engine.Engine - INFO - [generated in 0.00070s] ('Jonu sharma',)
2025-09-22 23:19:11,232 - main - INFO - Creating a  new course = DBMS
2025-09-22 23:19:11,236 - sqlalchemy.engine.Engine - INFO - INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`) VALUES (%s, %s, %s)
2025-09-22 23:19:11,236 - sqlalchemy.engine.Engine - INFO - [generated in 0.00077s] ('DBMS', 'Data base course', '5 month')
2025-09-22 23:19:11,239 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-09-22 23:19:11,241 - main - ERROR - Error creating course : (pymysql.err.OperationalError) (1054, "Unknown column 'Course_name' in 'field list'")
[SQL: INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`) VALUES (%s, %s, %s)]
[parameters: ('DBMS', 'Data base course', '5 month')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 192, in execute
    self._adapt_connection._handle_exception(error)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 330, in _handle_exception
    raise error.with_traceback(exc_info[2])
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 190, in execute
    return self.await_(self._execute_async(operation, parameters))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 213, in _execute_async
    result = await self._cursor.execute(operation, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 683, in _read_query_result
    await result.read()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 652, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'Course_name' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\app\routes\routes.py", line 170, in create_course
    new_courses =await crud.create_course(db,course)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\app\crud.py", line 25, in create_course
    await db.commit()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 1014, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4345, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4480, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4441, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        insert,
        ^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
        statement,
        params,
        execution_options=execution_options,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1419, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\sql\elements.py", line 526, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1641, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 192, in execute
    self._adapt_connection._handle_exception(error)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 330, in _handle_exception
    raise error.with_traceback(exc_info[2])
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 190, in execute
    return self.await_(self._execute_async(operation, parameters))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 213, in _execute_async
    result = await self._cursor.execute(operation, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 683, in _read_query_result
    await result.read()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 652, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'Course_name' in 'field list'")
[SQL: INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`) VALUES (%s, %s, %s)]
[parameters: ('DBMS', 'Data base course', '5 month')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-09-22 23:19:40,416 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:19:40,417 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:19:40,419 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:19:40,419 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:19:40,420 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:19:40,421 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:19:40,422 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:19:40,423 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:19:40,424 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:19:40,428 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:19:40,429 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:19:40,432 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:19:47,571 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:19:47,579 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.username, users.email, users.hashed_password, users.`role`, users.otp, users.otp_expiry, users.created_at, users.updated_at 
FROM users 
WHERE users.username = %s
2025-09-22 23:19:47,579 - sqlalchemy.engine.Engine - INFO - [generated in 0.00093s] ('Jonu sharma',)
2025-09-22 23:19:47,584 - main - INFO - Creating a  new course = DBMS
2025-09-22 23:19:47,587 - sqlalchemy.engine.Engine - INFO - INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`) VALUES (%s, %s, %s)
2025-09-22 23:19:47,587 - sqlalchemy.engine.Engine - INFO - [generated in 0.00068s] ('DBMS', 'Data base course', '5')
2025-09-22 23:19:47,590 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-09-22 23:19:47,591 - main - ERROR - Error creating course : (pymysql.err.OperationalError) (1054, "Unknown column 'Course_name' in 'field list'")
[SQL: INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`) VALUES (%s, %s, %s)]
[parameters: ('DBMS', 'Data base course', '5')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 192, in execute
    self._adapt_connection._handle_exception(error)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 330, in _handle_exception
    raise error.with_traceback(exc_info[2])
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 190, in execute
    return self.await_(self._execute_async(operation, parameters))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 213, in _execute_async
    result = await self._cursor.execute(operation, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 683, in _read_query_result
    await result.read()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 652, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'Course_name' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\app\routes\routes.py", line 170, in create_course
    new_courses =await crud.create_course(db,course)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\app\crud.py", line 25, in create_course
    await db.commit()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 1014, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4345, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4480, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4441, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        insert,
        ^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
        statement,
        params,
        execution_options=execution_options,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1419, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\sql\elements.py", line 526, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1641, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 192, in execute
    self._adapt_connection._handle_exception(error)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 330, in _handle_exception
    raise error.with_traceback(exc_info[2])
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 190, in execute
    return self.await_(self._execute_async(operation, parameters))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 213, in _execute_async
    result = await self._cursor.execute(operation, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 683, in _read_query_result
    await result.read()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 652, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'Course_name' in 'field list'")
[SQL: INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`) VALUES (%s, %s, %s)]
[parameters: ('DBMS', 'Data base course', '5')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-09-22 23:22:28,439 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:22:28,439 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:22:28,442 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:22:28,442 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:22:28,443 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:22:28,444 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:22:28,445 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:22:28,446 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:22:28,446 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:22:28,450 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:22:28,451 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:22:28,466 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:22:37,157 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:22:37,157 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:22:37,160 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:22:37,160 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:22:37,161 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:22:37,162 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:22:37,163 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:22:37,164 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:22:37,164 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:22:37,168 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:22:37,168 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:22:37,171 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:24:38,408 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:24:38,409 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:24:38,411 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:24:38,454 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:24:38,455 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:24:38,457 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:24:38,463 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:24:38,465 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:24:38,473 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:24:38,480 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:24:38,484 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:24:38,497 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:24:48,131 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:24:48,131 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:24:48,133 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:24:48,134 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:24:48,135 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:24:48,135 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:24:48,137 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:24:48,138 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:24:48,138 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:24:48,142 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:24:48,143 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:24:48,146 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:24:52,343 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:24:52,348 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.username, users.email, users.hashed_password, users.`role`, users.otp, users.otp_expiry, users.created_at, users.updated_at 
FROM users 
WHERE users.username = %s
2025-09-22 23:24:52,349 - sqlalchemy.engine.Engine - INFO - [generated in 0.00113s] ('Jonu sharma',)
2025-09-22 23:24:52,355 - main - INFO - Creating a  new course = DBMS
2025-09-22 23:24:52,358 - sqlalchemy.engine.Engine - INFO - INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`) VALUES (%s, %s, %s)
2025-09-22 23:24:52,358 - sqlalchemy.engine.Engine - INFO - [generated in 0.00072s] ('DBMS', 'Data base course', '5')
2025-09-22 23:24:52,360 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-09-22 23:24:52,362 - main - ERROR - Error creating course : (pymysql.err.OperationalError) (1054, "Unknown column 'Course_name' in 'field list'")
[SQL: INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`) VALUES (%s, %s, %s)]
[parameters: ('DBMS', 'Data base course', '5')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 192, in execute
    self._adapt_connection._handle_exception(error)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 330, in _handle_exception
    raise error.with_traceback(exc_info[2])
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 190, in execute
    return self.await_(self._execute_async(operation, parameters))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 213, in _execute_async
    result = await self._cursor.execute(operation, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 683, in _read_query_result
    await result.read()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 652, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'Course_name' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\app\routes\routes.py", line 170, in create_course
    new_courses =await crud.create_course(db,course)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\app\crud.py", line 25, in create_course
    await db.commit()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 1014, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4345, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4480, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4441, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        insert,
        ^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
        statement,
        params,
        execution_options=execution_options,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1419, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\sql\elements.py", line 526, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1641, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 192, in execute
    self._adapt_connection._handle_exception(error)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 330, in _handle_exception
    raise error.with_traceback(exc_info[2])
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 190, in execute
    return self.await_(self._execute_async(operation, parameters))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 213, in _execute_async
    result = await self._cursor.execute(operation, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 683, in _read_query_result
    await result.read()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 652, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'Course_name' in 'field list'")
[SQL: INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`) VALUES (%s, %s, %s)]
[parameters: ('DBMS', 'Data base course', '5')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-09-22 23:27:51,173 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:27:51,174 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:27:51,176 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:27:51,176 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:27:51,177 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:27:51,178 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:27:51,180 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:27:51,181 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:27:51,181 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:27:51,187 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:27:51,187 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:27:51,190 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:27:57,143 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:27:57,150 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.username, users.email, users.hashed_password, users.`role`, users.otp, users.otp_expiry, users.created_at, users.updated_at 
FROM users 
WHERE users.username = %s
2025-09-22 23:27:57,151 - sqlalchemy.engine.Engine - INFO - [generated in 0.00067s] ('Jonu sharma',)
2025-09-22 23:27:57,155 - main - INFO - Creating a  new course = DBMS
2025-09-22 23:27:57,157 - sqlalchemy.engine.Engine - INFO - INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`) VALUES (%s, %s, %s)
2025-09-22 23:27:57,158 - sqlalchemy.engine.Engine - INFO - [generated in 0.00063s] ('DBMS', 'Data base course', '5')
2025-09-22 23:27:57,160 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-09-22 23:27:57,161 - main - ERROR - Error creating course : (pymysql.err.OperationalError) (1054, "Unknown column 'Course_name' in 'field list'")
[SQL: INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`) VALUES (%s, %s, %s)]
[parameters: ('DBMS', 'Data base course', '5')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 192, in execute
    self._adapt_connection._handle_exception(error)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 330, in _handle_exception
    raise error.with_traceback(exc_info[2])
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 190, in execute
    return self.await_(self._execute_async(operation, parameters))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 213, in _execute_async
    result = await self._cursor.execute(operation, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 683, in _read_query_result
    await result.read()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 652, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'Course_name' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\app\routes\routes.py", line 170, in create_course
    new_courses =await crud.create_course(db,course)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\app\crud.py", line 25, in create_course
    await db.commit()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 1014, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4345, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4480, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4441, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        insert,
        ^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
        statement,
        params,
        execution_options=execution_options,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1419, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\sql\elements.py", line 526, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1641, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 192, in execute
    self._adapt_connection._handle_exception(error)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 330, in _handle_exception
    raise error.with_traceback(exc_info[2])
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 190, in execute
    return self.await_(self._execute_async(operation, parameters))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 213, in _execute_async
    result = await self._cursor.execute(operation, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 683, in _read_query_result
    await result.read()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 652, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'Course_name' in 'field list'")
[SQL: INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`) VALUES (%s, %s, %s)]
[parameters: ('DBMS', 'Data base course', '5')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-09-22 23:30:08,749 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:30:08,750 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:30:08,752 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:30:08,753 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:30:08,754 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:30:08,754 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:30:08,757 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:30:08,758 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:30:08,759 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:30:08,764 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:30:08,765 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:30:08,768 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:30:33,199 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:30:33,204 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.username, users.email, users.hashed_password, users.`role`, users.otp, users.otp_expiry, users.created_at, users.updated_at 
FROM users 
WHERE users.username = %s
2025-09-22 23:30:33,205 - sqlalchemy.engine.Engine - INFO - [generated in 0.00068s] ('Jonu sharma',)
2025-09-22 23:30:33,209 - main - INFO - Creating a  new course = DBMS
2025-09-22 23:30:33,212 - sqlalchemy.engine.Engine - INFO - INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`, created_at, updated_at) VALUES (%s, %s, %s, now(), now())
2025-09-22 23:30:33,212 - sqlalchemy.engine.Engine - INFO - [generated in 0.00068s] ('DBMS', 'Data base course', '5')
2025-09-22 23:30:33,214 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-09-22 23:30:33,216 - main - ERROR - Error creating course : (pymysql.err.OperationalError) (1054, "Unknown column 'Course_name' in 'field list'")
[SQL: INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`, created_at, updated_at) VALUES (%s, %s, %s, now(), now())]
[parameters: ('DBMS', 'Data base course', '5')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 192, in execute
    self._adapt_connection._handle_exception(error)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 330, in _handle_exception
    raise error.with_traceback(exc_info[2])
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 190, in execute
    return self.await_(self._execute_async(operation, parameters))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 213, in _execute_async
    result = await self._cursor.execute(operation, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 683, in _read_query_result
    await result.read()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 652, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'Course_name' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\app\routes\routes.py", line 170, in create_course
    new_courses =await crud.create_course(db,course)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\app\crud.py", line 25, in create_course
    await db.commit()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 1014, in commit
    await greenlet_spawn(self.sync_session.commit)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 203, in greenlet_spawn
    result = context.switch(value)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "<string>", line 2, in commit
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    ~~~~~~~~~~~~~~~~~~^^
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4345, in flush
    self._flush(objects)
    ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4480, in _flush
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 224, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\session.py", line 4441, in _flush
    flush_context.execute()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    ~~~~~~~~~~~^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.mapper,
        ^^^^^^^^^^^^
        uow.states_for_mapper_hierarchy(self.mapper, False, False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        uow,
        ^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        base_mapper,
        ^^^^^^^^^^^^
    ...<3 lines>...
        insert,
        ^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
        statement,
        params,
        execution_options=execution_options,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1419, in execute
    return meth(
        self,
        distilled_parameters,
        execution_options or NO_OPTIONS,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\sql\elements.py", line 526, in _execute_on_connection
    return connection._execute_clauseelement(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, distilled_params, execution_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1641, in _execute_clauseelement
    ret = self._execute_context(
        dialect,
    ...<8 lines>...
        cache_hit=cache_hit,
    )
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        dialect, context, statement, parameters
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        e, str_statement, effective_parameters, cursor, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        cursor, str_statement, effective_parameters, context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\engine\default.py", line 951, in do_execute
    cursor.execute(statement, parameters)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 192, in execute
    self._adapt_connection._handle_exception(error)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 330, in _handle_exception
    raise error.with_traceback(exc_info[2])
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 190, in execute
    return self.await_(self._execute_async(operation, parameters))
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\sqlalchemy\connectors\asyncio.py", line 213, in _execute_async
    result = await self._cursor.execute(operation, parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 239, in execute
    await self._query(query)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\cursors.py", line 457, in _query
    await conn.query(q)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 683, in _read_query_result
    await result.read()
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\aiomysql\connection.py", line 652, in _read_packet
    packet.raise_for_error()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\hare krishna\OneDrive\Desktop\College_Management\Backend\env\Lib\site-packages\pymysql\err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'Course_name' in 'field list'")
[SQL: INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`, created_at, updated_at) VALUES (%s, %s, %s, now(), now())]
[parameters: ('DBMS', 'Data base course', '5')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-09-22 23:33:46,826 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:33:46,827 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:33:46,829 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:33:46,830 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:33:46,831 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:33:46,831 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:33:46,833 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:33:46,834 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:33:46,834 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:33:46,840 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:33:46,841 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:33:46,847 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-09-22 23:34:06,002 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:34:06,002 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:34:06,004 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:34:06,005 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:34:06,006 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:34:06,006 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:34:06,008 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:34:06,009 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:34:06,009 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:34:06,014 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:34:06,015 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:34:06,021 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-09-22 23:35:38,401 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:35:38,401 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:38,403 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:35:38,404 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:38,405 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:35:38,405 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:38,407 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:35:38,408 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:35:38,408 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:38,414 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:35:38,415 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:38,419 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-09-22 23:35:41,984 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:35:41,985 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:41,986 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:35:41,987 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:41,988 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:35:41,988 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:41,990 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:35:41,991 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:35:41,991 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:41,996 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:35:41,997 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:42,001 - sqlalchemy.engine.Engine - INFO - 
CREATE TABLE courses (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	`Course_name` VARCHAR(50) NOT NULL, 
	`Course_desc` VARCHAR(300), 
	`Course_duration` VARCHAR(40), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id)
)


2025-09-22 23:35:42,002 - sqlalchemy.engine.Engine - INFO - [no key 0.00072s] ()
2025-09-22 23:35:42,036 - sqlalchemy.engine.Engine - INFO - CREATE INDEX ix_courses_id ON courses (id)
2025-09-22 23:35:42,036 - sqlalchemy.engine.Engine - INFO - [no key 0.00069s] ()
2025-09-22 23:35:42,073 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:35:51,782 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:35:51,782 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:51,784 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:35:51,785 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:51,786 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:35:51,786 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:51,788 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:35:51,789 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:35:51,789 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:51,793 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:35:51,794 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:35:51,798 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:35:56,822 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:35:56,830 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.username, users.email, users.hashed_password, users.`role`, users.otp, users.otp_expiry, users.created_at, users.updated_at 
FROM users 
WHERE users.username = %s
2025-09-22 23:35:56,830 - sqlalchemy.engine.Engine - INFO - [generated in 0.00083s] ('Jonu sharma',)
2025-09-22 23:35:56,834 - main - INFO - Creating a  new course = DBMS
2025-09-22 23:35:56,837 - sqlalchemy.engine.Engine - INFO - INSERT INTO courses (`Course_name`, `Course_desc`, `Course_duration`, created_at, updated_at) VALUES (%s, %s, %s, now(), now())
2025-09-22 23:35:56,837 - sqlalchemy.engine.Engine - INFO - [generated in 0.00069s] ('DBMS', 'Data base course', '5')
2025-09-22 23:35:56,851 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:35:56,858 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:35:56,862 - sqlalchemy.engine.Engine - INFO - SELECT courses.id, courses.`Course_name`, courses.`Course_desc`, courses.`Course_duration`, courses.created_at, courses.updated_at 
FROM courses 
WHERE courses.id = %s
2025-09-22 23:35:56,863 - sqlalchemy.engine.Engine - INFO - [generated in 0.00080s] (1,)
2025-09-22 23:35:56,865 - main - INFO - Course created successfully with course name : DBMS
2025-09-22 23:35:56,870 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-09-22 23:36:25,715 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:36:25,716 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:25,718 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:36:25,718 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:25,719 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:36:25,720 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:25,722 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:36:25,723 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:36:25,723 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:25,727 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:36:25,728 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:25,731 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:36:28,647 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:36:28,648 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:28,649 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:36:28,650 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:28,651 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:36:28,651 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:28,654 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:36:28,654 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:36:28,655 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:28,659 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:36:28,660 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:28,664 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:36:37,618 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:36:37,618 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:37,620 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:36:37,621 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:37,622 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:36:37,622 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:37,624 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:36:37,625 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:36:37,626 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:37,631 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:36:37,632 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:37,635 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:36:42,697 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:36:42,698 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:42,700 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:36:42,700 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:42,701 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:36:42,702 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:42,704 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:36:42,704 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:36:42,705 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:42,708 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:36:42,709 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:42,711 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:36:54,726 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:36:54,726 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:54,728 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:36:54,729 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:54,730 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:36:54,730 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:54,732 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:36:54,733 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:36:54,733 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:54,737 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:36:54,738 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:54,742 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:36:57,435 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:36:57,436 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:57,438 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:36:57,439 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:57,440 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:36:57,440 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:57,442 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:36:57,443 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:36:57,443 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:57,447 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:36:57,448 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:36:57,451 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:37:00,325 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:37:00,326 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:00,328 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:37:00,329 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:00,330 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:37:00,330 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:00,332 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:37:00,333 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:37:00,333 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:00,337 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:37:00,338 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:00,342 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:37:03,243 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:37:03,244 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:03,246 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:37:03,246 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:03,247 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:37:03,248 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:03,250 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:37:03,250 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:37:03,251 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:03,255 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:37:03,255 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:03,258 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:37:05,965 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:37:05,966 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:05,968 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:37:05,968 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:05,969 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:37:05,970 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:05,972 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:37:05,972 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:37:05,973 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:05,976 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:37:05,977 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:05,979 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:37:38,354 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:37:38,355 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:38,357 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:37:38,357 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:38,358 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:37:38,359 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:38,360 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:37:38,361 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:37:38,362 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:38,365 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:37:38,365 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:37:38,369 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:39:15,378 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:39:15,379 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:39:15,381 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:39:15,382 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:39:15,383 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:39:15,383 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:39:15,385 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:39:15,386 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:39:15,386 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:39:15,391 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:39:15,392 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:39:15,399 - sqlalchemy.engine.Engine - INFO - 
CREATE TABLE courses (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	`Course_name` VARCHAR(50) NOT NULL, 
	`Course_desc` VARCHAR(300), 
	`Course_credit` VARCHAR(40), 
	`Course_duration` VARCHAR(40), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (id)
)


2025-09-22 23:39:15,400 - sqlalchemy.engine.Engine - INFO - [no key 0.00095s] ()
2025-09-22 23:39:15,438 - sqlalchemy.engine.Engine - INFO - CREATE INDEX ix_courses_id ON courses (id)
2025-09-22 23:39:15,439 - sqlalchemy.engine.Engine - INFO - [no key 0.00081s] ()
2025-09-22 23:39:15,475 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:41:38,544 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:41:38,544 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:41:38,547 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:41:38,547 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:41:38,548 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:41:38,549 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:41:38,551 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:41:38,552 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:41:38,552 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:41:38,558 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:41:38,558 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:41:38,561 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:41:45,922 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-22 23:41:45,923 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:41:45,925 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-22 23:41:45,925 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:41:45,926 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-22 23:41:45,927 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:41:45,928 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:41:45,929 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-22 23:41:45,930 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:41:45,934 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-22 23:41:45,935 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-22 23:41:45,939 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:42:07,435 - main - INFO - Creating a  new course = DBMS
2025-09-22 23:42:07,438 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:42:07,442 - sqlalchemy.engine.Engine - INFO - INSERT INTO courses (`Course_name`, `Course_desc`, `Course_credit`, `Course_duration`, created_at, updated_at) VALUES (%s, %s, %s, %s, now(), now())
2025-09-22 23:42:07,443 - sqlalchemy.engine.Engine - INFO - [generated in 0.00088s] ('DBMS', 'Data base course', '4', '5')
2025-09-22 23:42:07,447 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-22 23:42:07,471 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-22 23:42:07,478 - sqlalchemy.engine.Engine - INFO - SELECT courses.id, courses.`Course_name`, courses.`Course_desc`, courses.`Course_credit`, courses.`Course_duration`, courses.created_at, courses.updated_at 
FROM courses 
WHERE courses.id = %s
2025-09-22 23:42:07,478 - sqlalchemy.engine.Engine - INFO - [generated in 0.00089s] (1,)
2025-09-22 23:42:07,481 - main - INFO - Course created successfully with course name : DBMS
2025-09-22 23:42:07,482 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-09-23 20:59:14,206 - sqlalchemy.engine.Engine - INFO - SELECT DATABASE()
2025-09-23 20:59:14,207 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-23 20:59:14,214 - sqlalchemy.engine.Engine - INFO - SELECT @@sql_mode
2025-09-23 20:59:14,214 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-23 20:59:14,216 - sqlalchemy.engine.Engine - INFO - SELECT @@lower_case_table_names
2025-09-23 20:59:14,216 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-23 20:59:14,220 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-23 20:59:14,220 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users`
2025-09-23 20:59:14,221 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-23 20:59:14,281 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`users_archive`
2025-09-23 20:59:14,282 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-23 20:59:14,286 - sqlalchemy.engine.Engine - INFO - DESCRIBE `college_management`.`courses`
2025-09-23 20:59:14,286 - sqlalchemy.engine.Engine - INFO - [raw sql] ()
2025-09-23 20:59:14,292 - sqlalchemy.engine.Engine - INFO - 
CREATE TABLE users_archive (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	username VARCHAR(100), 
	email VARCHAR(100), 
	`role` VARCHAR(50), 
	created_at DATETIME, 
	deleted_at DATETIME, 
	PRIMARY KEY (id)
)


2025-09-23 20:59:14,293 - sqlalchemy.engine.Engine - INFO - [no key 0.00075s] ()
2025-09-23 20:59:14,376 - sqlalchemy.engine.Engine - INFO - CREATE INDEX ix_users_archive_id ON users_archive (id)
2025-09-23 20:59:14,377 - sqlalchemy.engine.Engine - INFO - [no key 0.00058s] ()
2025-09-23 20:59:14,413 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-23 21:02:25,394 - main - INFO - Login attempt for username = Jonu Sharma
2025-09-23 21:02:25,398 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-23 21:02:25,411 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.username, users.email, users.hashed_password, users.`role`, users.otp, users.otp_expiry, users.created_at, users.updated_at 
FROM users 
WHERE users.username = %s
2025-09-23 21:02:25,412 - sqlalchemy.engine.Engine - INFO - [generated in 0.00122s] ('Jonu Sharma',)
2025-09-23 21:02:25,986 - main - INFO - User login successful: Jonu Sharma
2025-09-23 21:02:25,999 - sqlalchemy.engine.Engine - INFO - ROLLBACK
2025-09-23 21:03:03,897 - sqlalchemy.engine.Engine - INFO - BEGIN (implicit)
2025-09-23 21:03:03,898 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.username, users.email, users.hashed_password, users.`role`, users.otp, users.otp_expiry, users.created_at, users.updated_at 
FROM users 
WHERE users.username = %s
2025-09-23 21:03:03,898 - sqlalchemy.engine.Engine - INFO - [cached since 38.49s ago] ('Jonu sharma',)
2025-09-23 21:03:03,902 - main - INFO - Delete user with id=19 by Jonu sharma
2025-09-23 21:03:03,904 - sqlalchemy.engine.Engine - INFO - SELECT users.id, users.username, users.email, users.hashed_password, users.`role`, users.otp, users.otp_expiry, users.created_at, users.updated_at 
FROM users 
WHERE users.id = %s
2025-09-23 21:03:03,904 - sqlalchemy.engine.Engine - INFO - [generated in 0.00076s] (19,)
2025-09-23 21:03:03,910 - sqlalchemy.engine.Engine - INFO - INSERT INTO users_archive (id, username, email, `role`, created_at, deleted_at) VALUES (%s, %s, %s, %s, %s, %s)
2025-09-23 21:03:03,910 - sqlalchemy.engine.Engine - INFO - [generated in 0.00064s] (19, ' Sharma', 'Ra@gmail.com', 'student', datetime.datetime(2025, 9, 22, 22, 40, 40), datetime.datetime(2025, 9, 23, 15, 33, 3, 907048))
2025-09-23 21:03:03,923 - sqlalchemy.engine.Engine - INFO - DELETE FROM users WHERE users.id = %s
2025-09-23 21:03:03,923 - sqlalchemy.engine.Engine - INFO - [generated in 0.00066s] (19,)
2025-09-23 21:03:03,929 - sqlalchemy.engine.Engine - INFO - COMMIT
2025-09-23 21:03:03,935 - main - INFO - User 19 deleted and archived by Jonu sharma
